<a href="https://colab.research.google.com/github/rasaltejas/ml-practice-projects/blob/rasaltejas-patch-1/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Linear Algebra**
A. Vectors

A student can be represented as:

math marks = 86

physics marks = 82

chemistry marks = 88

     v=[86,82,88]
     
vector = collection of features


In [16]:
#Scalars
x = 5
y = 10.5
print(x)
print(y)

5
10.5


In [17]:
#Vector
import numpy as np
v = np.array([25, 30, 80])
print(v)
print(v.shape)
print(v.ndim)

[25 30 80]
(3,)
1


In [18]:
#Matrix
# Rows = students
# Columns = subjects
import numpy as np
students = np.array([
    [80, 50, 80],
    [80, 70, 90],
    [50, 60, 30]]
)
print(students)
print(students.shape)
print(students.ndim)  #used for check dimensions

[[80 50 80]
 [80 70 90]
 [50 60 30]]
(3, 3)
2
