<a href="https://colab.research.google.com/github/rasaltejas/ml-practice-projects/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
#Scalars
x = 5
y = 10.5
print(x)
print(y)

5
10.5


In [14]:
#Vector
import numpy as np
v = np.array([25, 30, 80])
print(v)
print(v.shape)
print(v.ndim)

[25 30 80]
(3,)
1


In [15]:
#Matrix
# Rows = students
# Columns = subjects
import numpy as np
students = np.array([
    [80, 50, 80],
    [80, 70, 90],
    [50, 60, 30]]
)
print(students)
print(students.shape)
print(students.ndim)  #used for check dimensions

[[80 50 80]
 [80 70 90]
 [50 60 30]]
(3, 3)
2


In [ ]:
import numpy as np

# Calculate the total marks for each student (sum across rows)
total_marks_per_student = np.sum(students, axis=1)
print("Total marks per student:")
print(total_marks_per_student)